Add multiple MGT support per run (Rx different from Tx), error count feature, and BER specification
vfinotti/MGT-Autotuning pull request #2
Opened 2019-03-26 22:58 UTC by RobertGlein

Hi Vitor,

I improved and extended your scripts a bit.

Best,
Robért

2019-05-20 20:54 UTC, vfinotti requested changes
Hi, thanks once more for contributing to the repository! I have made some comments inline. I also have some request/suggestions (which are applicable to all the files) that I'd like to discuss before including the commits on the repository.

- Overall comments
  - It's quite difficult to comment because several changes are made in each commit. For example, in the commit "Added support for different Rx and Tx." (hash 811049d), there are changes related to all the improvements (different rx/tx support, bitstream automatic programming, etc). Organizing commits with more atomic changes is suggested for future contributions.
  - There are several pieces of code commented out. If they are not fundamental for understanding the script, perhaps removing them would result in a cleaner code.
  - Some of the commands on the .tcl and .sh files use absolute paths, and would only work on a particular setup. A possible way to reduce the impact of that would creating variables at the beginning of the file with the parameters particular to the setup, so new users can immediately know where they should do the changes in order to use the scripts
  - Although the inclusion of different .tcl files makes the project richer with more usage examples, perhaps leaving the configuration available on "config.ini" files as an example case for a more generic board such as kc705 would be easier to understand for newcomers.

2019-05-20 20:54 UTC, vfinotti commented on README.md
> +
Given that this is also related to the preparation of the boards to run the autotuning, I would suggest including this part at the end of the "Preparing the boards" section, immediately before the "Setting the config.ini" section. I would also be a bit more explicit in what that command does (Open the vivado instances, program the boards with the bitstream, and run the autotuning process)

2019-05-20 20:54 UTC, vfinotti commented on autotuning/automate/hw_vcu118.tcl
> +#start_gui
Is the commented code important for understanding the script? If it's not, could it be removed for a cleaner code?

Also, could the absolute path be avoided or be substituted by a variable declared at the begining of the script?"

2019-05-20 20:54 UTC, vfinotti commented on autotuning/automate/hw_yugevu1.tcl
> +#start_gui
Is the commented code important for understanding the script? If it's not, could it be removed for a cleaner code?

Also, could the absolute path be avoided or be substituted by a variable declared at the begining of the script?"

2019-05-20 20:54 UTC, vfinotti commented on autotuning/automate/hw_yugevu2.tcl
> +refresh_hw_device [lindex [get_hw_devices xcvu080_0] 0]
Is the commented code important for understanding the script? If it's not, could it be removed for a cleaner code?

Also, could the absolute path be avoided or be substituted by a variable declared at the begining of the script?"

2019-05-20 20:54 UTC, vfinotti commented on autotuning/automate/run_MGT_autotune.sh
> +#echo -e " \033[0;31m Ensure that both FPGAs are configured with the corrrect IBERT design! \033[0m "
Is the commented code important for understanding the script? If it's not, could it be removed for a cleaner code?

2019-05-20 20:54 UTC, vfinotti commented on autotuning/classes/pyIBERT.py
> +#    print("commit_hw_sio" + " [" + obj + "]")
Is the commented code important for understanding the script? If it's not, could it be removed for a cleaner code?

2019-05-20 20:54 UTC, vfinotti commented on autotuning/config.ini
> +# TX
Although the inclusion of different .tcl files makes the project richer with more usage examples, perhaps leaving the configuration available on "config.ini" files as an example case for a more generic board, such as kc705 would be easier to understand for newcomers. Besides, does setting the target0_freq as "0" work? I'm quite lost in what setting the communication freq to "0" would cause.

2019-05-20 20:54 UTC, vfinotti commented on autotuning/config.ini
> +
Please avoid inserting newline or whitespaces at the files without a specific purpose

2019-05-20 20:54 UTC, vfinotti commented on autotuning/config.ini
> +mgt = X0Y0,X0Y1,X0Y2,X0Y3,X0Y4,X0Y5,X0Y6,X0Y7,X0Y8,X0Y9,X0Y10,X0Y11
Given that a "mgt_tx" is used for the transmitter, shouldn't the other variable be called "mgt_rx" for consistency?

2019-05-20 20:54 UTC, vfinotti commented on autotuning/config.ini
> +         700 mV,800 mV,850 mV,900 mV,950 mV,1000 mV,1100 mV
Please avoid inserting newline or whitespaces at the files without a specific purpose

2019-05-20 20:54 UTC, vfinotti commented on autotuning/run.py
> +#                                      Added error counter und BER as in config
"Added error counter und BER as in config" contains a typo. Correct to "Added error counter and BER as in config"

2019-05-20 20:54 UTC, vfinotti commented on autotuning/run.py
>  mgt = config.get('mgt_parameters','mgt')
Consider renaming to "mgt_rx" for consistency with the variable "mgt_tx"

2019-05-20 20:54 UTC, vfinotti commented on autotuning/run.py
>                      link = rcv.get_property("LOGIC.LINK", obj)
Consider renaming "obj" to "obj_rx" for consistency

2019-05-21 16:18 UTC, RobertGlein commented on README.md
> +
I split the description. One part in the "prepare" section, the other in the "run" section.

2019-05-21 22:25 UTC, RobertGlein commented on autotuning/automate/hw_vcu118.tcl
> +#start_gui
I cleaned up the code and put in relative paths.

2019-05-21 22:26 UTC, RobertGlein commented on autotuning/automate/hw_yugevu1.tcl
> +#start_gui
I cleaned up the code and put in relative paths.

2019-05-21 22:26 UTC, RobertGlein commented on autotuning/automate/hw_yugevu2.tcl
> +refresh_hw_device [lindex [get_hw_devices xcvu080_0] 0]
I cleaned up the code and put in relative paths.

2019-05-21 22:27 UTC, RobertGlein commented on autotuning/automate/run_MGT_autotune.sh
> +#echo -e " \033[0;31m Ensure that both FPGAs are configured with the corrrect IBERT design! \033[0m "
I cleaned up the code.

2019-05-21 22:28 UTC, RobertGlein commented on autotuning/classes/pyIBERT.py
> +#    print("commit_hw_sio" + " [" + obj + "]")
I cleaned up the code.

2019-05-21 22:31 UTC, RobertGlein commented on autotuning/config.ini
> +# TX
I agree with you but unfortunately, I do not have two evaluation boards. Can you please test if you have the HW available?
The 0 is for xvc only and its speed is defined by the Ethernet connection. I added a comment.

2019-05-21 22:32 UTC, RobertGlein commented on autotuning/config.ini
> +
ok

2019-05-21 22:38 UTC, RobertGlein commented on autotuning/config.ini
> +mgt = X0Y0,X0Y1,X0Y2,X0Y3,X0Y4,X0Y5,X0Y6,X0Y7,X0Y8,X0Y9,X0Y10,X0Y11
Ok, I refactored it.

2019-05-21 22:39 UTC, RobertGlein commented on autotuning/config.ini
> +         700 mV,800 mV,850 mV,900 mV,950 mV,1000 mV,1100 mV
ok

2019-05-21 22:41 UTC, RobertGlein commented on autotuning/run.py
> +#                                      Added error counter und BER as in config
changed

2019-05-21 22:42 UTC, RobertGlein commented on autotuning/run.py
>  mgt = config.get('mgt_parameters','mgt')
done

2019-05-22 15:31 UTC, RobertGlein commented on autotuning/run.py
>                      link = rcv.get_property("LOGIC.LINK", obj)
done

2019-05-22 16:23 UTC, RobertGlein commented
I tried to improve the code based on your suggestions. The latest push works with my examples. 
Can you please adapt the necessary files and make an example work for two kc705, because I do not have two evaluation boards?

2019-05-22 17:35 UTC, vfinotti approved these changes

2019-05-22 17:36 UTC, merged

2019-05-22 17:37 UTC, vfinotti commented
Thanks for the changes! I'll work on the kc705 example, but for the moment I'm merging your code into the repository. Cheers!